version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:5432/test
      - SPRING_DATASOURCE_USERNAME=openfabric
      - SPRING_DATASOURCE_PASSWORD=9c231a1c61a5fe322dd1

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres